import DB from '../DB';
import fs from 'fs';
import { MenuInputInterface, ShopController } from '../DB/controller/Shop/ShopController';
import dotenv from 'dotenv';
import Shop, { FoodCategory, ShopCategory } from '../DB/models/Shop';
import Image from '../DB/models/Image';
dotenv.config();

(async () => {
  await DB.connect();
  let init = `<?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <!-- Generated by Web-Site-Map.com -->
  <url><loc>https://caufooding.com/</loc><changefreq>daily</changefreq><priority>1.00</priority></url>
  `;
  let shops = await Shop.find();
  for (const shop of shops) {
    console.log(``);
    init += `<url><loc>https://caufooding.com/shop/${shop._id}</loc><changefreq>daily</changefreq><priority>1.00</priority></url>\n`;
  }
  init += '</urlset>';
  console.log(init);
  fs.writeFileSync('src/lib/sitemap.xml', init);
  console.log('sitemap 변환 완료');
})();

// <?xml version="1.0" encoding="UTF-8"?>
// <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
// <!-- Generated by Web-Site-Map.com -->
// <url><loc>https://caufooding.com/</loc><changefreq>daily</changefreq><priority>1.00</priority></url>
// </urlset>
