import DB from '../DB';
import { ShopController } from '../DB/controller/Shop/ShopController';
import dotenv from 'dotenv';
dotenv.config();

interface Data {
  name: string;
  address: string;
  contact: string;
  category: string;
  foodCategory: string;
  closed: string;
  open: string;
  price?: number;
  latitude?: number;
  longitude?: number;
  location: string;
}

let data: Data[] = [
  {
    name: '초반식당',
    address: '서울시 동작구 흑석동 181-11 2F',
    contact: '02-813-2728',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '16:00 - 01:00',
    location: 'front',
  },
  {
    name: '우리집칼국수',
    address: '서울특별시 동작구 서달로12가길 13',
    contact: '02-822-0507',
    category: 'korean',
    foodCategory: '국수 / 면 요리',
    closed: '일',
    open: '11:00 - 19:30',
    location: 'hs_station',
  },
  {
    name: '맥도날드',
    address: '서울특별시 동작구 흑석로 84',
    contact: '070-7017-1417',
    category: 'western',
    foodCategory: '브런치 / 버거 / 샌드위치',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '가마로강정',
    address: '서울특별시 동작구 서달로 151',
    contact: '02-3280-0808',
    category: 'korean',
    foodCategory: '닭 / 오리 요리',
    closed: '',
    open: '11:00 - 24:00',
    location: 'hs_station',
  },
  {
    name: '정가네 고려왕족발',
    address: '서울특별시 동작구 서달로14나길 3',
    contact: '02-813-7879',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '일',
    open: '16:00 - 22:00',
    location: 'hs_station',
  },
  {
    name: '곱창스토브',
    address: '서울특별시 동작구 서달로15길 12',
    contact: '02-827-0531',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '치폴레옹',
    address: '서울특별시 동작구 흑석로 101-5',
    contact: '02-3280-0078',
    category: 'fusion',
    foodCategory: '닭 / 오리 요리',
    closed: '',
    open: '11:00 - 24:00',
    location: 'front',
  },
  {
    name: '해오름갈비',
    address: '서울특별시 동작구 서달로10길 11',
    contact: '02-824-8866',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '10:00 - 22:00',
    location: 'hs_station',
  },
  {
    name: '안동장',
    address: '서울특별시 동작구 흑석로 105-1',
    contact: '02-813-0572',
    category: 'chinese',
    foodCategory: '정통 중식 / 일반 중식',
    closed: '',
    open: '11:00 - 21:30',
    location: 'front',
  },
  {
    name: '봉평면옥',
    address: '서울특별시 동작구 서달로14나길 24-1',
    contact: '',
    category: 'korean',
    foodCategory: '국수 / 면 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '열정식당',
    address: '서울특별시 동작구 흑석로9길 6',
    contact: '02-815-0904',
    category: 'korean',
    foodCategory: '한정식 / 백반 / 정통 한식',
    closed: '일',
    open: '10:00 - 21:00',
    location: 'front',
  },
  {
    name: '올바른식당',
    address: '서울특별시 동작구 상도로 279 상일빌딩',
    contact: '02-815-5909',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'back',
  },
  {
    name: '스시초이',
    address: '서울특별시 동작구 흑석로6길 18',
    contact: '02-822-6477',
    category: 'japanese',
    foodCategory: '회 / 스시',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '하꼬멘',
    address: '서울특별시 동작구 흑석로9길 15',
    contact: '02-812-0455',
    category: 'japanese',
    foodCategory: '라멘 / 소바 / 우동',
    closed: '토, 일',
    open: '10:00 - 20:30',
    location: 'front',
  },
  {
    name: '쿵푸마라탕',
    address: '서울시 동작구 흑석동 190-25',
    contact: '',
    category: 'chinese',
    foodCategory: '기타 중식',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '원조소금구이',
    address: '서울특별시 동작구 서달로14길 16',
    contact: '02-815-2259',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '미소야',
    address: '서울특별시 동작구 흑석로 111',
    contact: '02-823-7304',
    category: 'japanese',
    foodCategory: '까스 요리',
    closed: '',
    open: '11:30 - 22:00',
    location: 'front',
  },
  {
    name: '사과나무왕돈까스',
    address: '서울특별시 동작구 흑석로9길 7',
    contact: '02-825-1831',
    category: 'school',
    foodCategory: '기타 한식',
    closed: '',
    open: '09:00 - 21:30',
    location: 'front',
  },
  {
    name: '황토정',
    address: '서울특별시 동작구 서달로13길 5-23',
    contact: '02-814-4467',
    category: 'korean',
    foodCategory: '한정식 / 백반 / 정통 한식',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '구공탄불고기',
    address: '서울특별시 동작구 서달로10길 8',
    contact: '02-812-2400',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '일',
    open: '11:00 - 22:00',
    location: 'hs_station',
  },
  {
    name: '포쉐프',
    address: '서울특별시 동작구 양녕로 274',
    contact: '02-6401-4568',
    category: 'other',
    foodCategory: '베트남 음식',
    closed: '첫째/마지막 일',
    open: '11:00 - 23:00',
    location: 'back',
  },
  {
    name: '엉터리생고기',
    address: '서울특별시 동작구 서달로14나길 5-1',
    contact: '02-814-3376',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '11:00 - 23:00',
    location: 'hs_station',
  },
  {
    name: '피자보이시나',
    address: '서울특별시 동작구 흑석로9길 6',
    contact: '02-815-6564',
    category: 'western',
    foodCategory: '이탈리안',
    closed: '',
    open: '11:00 - 22:30',
    location: 'front',
  },
  {
    name: '더진국',
    address: '서울특별시 동작구 흑석로 83-1',
    contact: '02-815-2229',
    category: 'korean',
    foodCategory: '탕 / 찌개 / 전골',
    closed: '',
    open: '00:00 - 24:00',
    location: 'front',
  },
  {
    name: '고기스토리',
    address: '서울특별시 동작구 흑석로8길 4',
    contact: '02-812-7894',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '미니자이언트',
    address: '서울특별시 동작구 흑석로 81-6 1F',
    contact: '02-3280-0907',
    category: 'western',
    foodCategory: '스테이크 / 바베큐',
    closed: '',
    open: '10:00 - 20:00',
    location: 'front',
  },
  {
    name: '투고샐러드',
    address: '서울특별시 동작구 흑석로13가길 43 1F',
    contact: '02-824-7060',
    category: 'western',
    foodCategory: '기타 양식',
    closed: '',
    open: '월-금: 10:00 - 22:00 토-일: 10:00 - 21:00',
    location: 'front',
  },
  {
    name: '곰팔이생고기',
    address: '서울특별시 동작구 서달로15길 7',
    contact: '02-813-0822',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '재팔이네닭발',
    address: '서울특별시 동작구 서달로14길 34',
    contact: '02-813-7541',
    category: 'korean',
    foodCategory: '닭 / 오리 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '진미순대',
    address: '서울특별시 동작구 서달로12가길 5',
    contact: '02-812-0539',
    category: 'korean',
    foodCategory: '탕 / 찌개 / 전골',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '허수아비',
    address: '서울특별시 동작구 서달로 158',
    contact: '02-3280-1187',
    category: 'korean',
    foodCategory: '기타 한식',
    closed: '',
    open: '11:00 - 21:00',
    location: 'hs_station',
  },
  {
    name: '엉터리양평해장국',
    address: '서울특별시 동작구 서달로14나길 8',
    contact: '02-822-3374',
    category: 'korean',
    foodCategory: '탕 / 찌개 / 전골',
    closed: '',
    open: '11:00 - 22:50',
    location: 'hs_station',
  },
  {
    name: '중문닭갈비',
    address: '서울시 동작구 흑석동 207-65',
    contact: '',
    category: 'korean',
    foodCategory: '닭 / 오리 요리',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '육반연반',
    address: '서울특별시 동작구 서달로14길 24 2F',
    contact: '010-3616-3609',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '18:00 - 02:00',
    location: 'hs_station',
  },
  {
    name: '포포인',
    address: '서울특별시 동작구 흑석로6길 61 중앙대학교 310관 B4',
    contact: '02-881-7439',
    category: 'other',
    foodCategory: '베트남 음식',
    closed: '일',
    open: '10:00 - 21:00',
    location: 'back',
  },
  {
    name: '흑석호치민',
    address: '서울특별시 동작구 서달로15길 20-5',
    contact: '02-826-0780',
    category: 'other',
    foodCategory: '베트남 음식',
    closed: '',
    open: '월-금: 11:00 - 21:00 토-일: 11:30 - 21:00',
    location: 'hs_station',
  },
  {
    name: '도리도리하찌',
    address: '서울특별시 동작구 흑석로13가길 43',
    contact: '02-999-4490',
    category: 'korean',
    foodCategory: '닭 / 오리 요리',
    closed: '일',
    open: '11:00 - 24:00',
    location: 'front',
  },
  {
    name: '고깃집',
    address: '서울특별시 동작구 서달로14길 46',
    contact: '02-3280-6888',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '16:00 - 24:00',
    location: 'hs_station',
  },
  {
    name: '준호가만드는즉석떡볶이',
    address: '서울특별시 동작구 흑석로 83-1',
    contact: '070-8771-8249',
    category: 'school',
    foodCategory: '기타 한식',
    closed: '',
    open: '10:30 - 20:00',
    location: 'front',
  },
  {
    name: '원할머니보쌈족발',
    address: '서울특별시 동작구 현충로 100-1',
    contact: '02-817-3336',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'front_far',
  },
  {
    name: '우뇽파스타',
    address: '서울특별시 동작구 서달로10길 10 2F',
    contact: '02-816-6338',
    category: 'western',
    foodCategory: '이탈리안',
    closed: '일',
    open: '12:00 - 21:00',
    location: 'hs_station',
  },
  {
    name: '라화쿵부',
    address: '서울특별시 동작구 흑석로13마길 65 1F',
    contact: '02-821-8313',
    category: 'chinese',
    foodCategory: '기타 중식',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '곱창의전설',
    address: '서울특별시 동작구 흑석로 87',
    contact: '02-817-1120',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '일',
    open: '15:00 - 01:00',
    location: 'front',
  },
  {
    name: '계단집',
    address: '서울시 동작구 흑석동 6-10',
    contact: '02-821-9867',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '첫째/셋째 일',
    open: '11:30 - 24:00',
    location: 'front_far',
  },
  {
    name: '서브웨이',
    address: '서울특별시 동작구 흑석로 79',
    contact: '02-815-6429',
    category: 'western',
    foodCategory: '브런치 / 버거 / 샌드위치',
    closed: '',
    open: '08:00 - 23:00',
    location: 'front',
  },
  {
    name: '고봉삼계탕',
    address: '서울특별시 동작구 서달로 166 1F',
    contact: '02-824-3339',
    category: 'korean',
    foodCategory: '탕 / 찌개 / 전골',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '명문본가왕족발과보쌈',
    address: '서울특별시 동작구 서달로10가길 1',
    contact: '02-817-9942',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '12:00 - 23:00',
    location: 'hs_station',
  },
  {
    name: '주주총회',
    address: '서울특별시 동작구 서달로14가길 9',
    contact: '02-812-6685',
    category: 'japanese',
    foodCategory: '해산물 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '마포최대포숯불갈매기돼지갈비',
    address: '서울특별시 동작구 서달로14길 11',
    contact: '02-817-0738',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '17:00 - 23:30',
    location: 'hs_station',
  },
  {
    name: '해랑',
    address: '서울특별시 동작구 흑석로 116',
    contact: '02-814-1400',
    category: 'japanese',
    foodCategory: '회 / 스시',
    closed: '',
    open: '18:00 - 02:00',
    location: 'hs_station',
  },
  {
    name: '중앙돼지마을',
    address: '서울특별시 동작구 흑석로 85-7',
    contact: '02-827-0608',
    category: 'korean',
    foodCategory: '한정식 / 백반 / 정통 한식',
    closed: '',
    open: '09:30 - 22:00',
    location: 'front',
  },
  {
    name: '청기와뼈다귀해장국',
    address: '서울특별시 동작구 흑석로 94',
    contact: '02-822-3963',
    category: 'korean',
    foodCategory: '탕 / 찌개 / 전골',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '유정쌈밥',
    address: '서울특별시 동작구 서달로13길 5-14',
    contact: '02-816-0338',
    category: 'korean',
    foodCategory: '한정식 / 백반 / 정통 한식',
    closed: '',
    open: '10:00 - 22:00',
    location: 'hs_station',
  },
  {
    name: '이탈리안 돈까스 칡불냉면',
    address: '서울특별시 동작구 흑석로9길 15',
    contact: '',
    category: 'korean',
    foodCategory: '기타 한식',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '동원참치',
    address: '서울특별시 동작구 흑석로 102 중앙대병원 B110',
    contact: '02-6293-3737',
    category: 'japanese',
    foodCategory: '회 / 스시',
    closed: '',
    open: '월-금: 11:00 - 22:00 토-일: 11:00 - 21:30',
    location: 'front',
  },
  {
    name: '타누키돈부리',
    address: '서울특별시 동작구 흑석로 91',
    contact: '02-812-9987',
    category: 'japanese',
    foodCategory: '돈부리 / 일본 카레 / 벤토',
    closed: '일',
    open: '10:30 - 21:30',
    location: 'front',
  },
  {
    name: '흑수돈',
    address: '서울특별시 동작구 서달로14나길 27',
    contact: '02-826-7278',
    category: 'korean',
    foodCategory: '기타 한식',
    closed: '',
    open: '10:50 - 20:40',
    location: 'hs_station',
  },
  {
    name: '리얼후라이',
    address: '서울특별시 동작구 흑석로 115 1F',
    contact: '02-813-1804',
    category: 'western',
    foodCategory: '닭 / 오리 요리',
    closed: '',
    open: '15:00 - 02:00',
    location: 'front',
  },
  {
    name: '도스마스',
    address: '서울특별시 동작구 흑석로13마길 65-3',
    contact: '02-3280-1818',
    category: 'other',
    foodCategory: '남미 음식',
    closed: '',
    open: '10:00 - 21:40',
    location: 'front',
  },
  {
    name: '스시톡톡',
    address: '서울특별시 동작구 흑석로 109 2F',
    contact: '02-812-5565',
    category: 'japanese',
    foodCategory: '회 / 스시',
    closed: '일',
    open: '10:30 - 22:00',
    location: 'front',
  },
  {
    name: '하노이별',
    address: '서울특별시 동작구 흑석로 81-5',
    contact: '02-3280-7470',
    category: 'other',
    foodCategory: '베트남 음식',
    closed: '',
    open: '월-금: 10:30 - 22:00 토-일: 10:30 - 21:00',
    location: 'front',
  },
  {
    name: '상도늘보리',
    address: '서울특별시 동작구 서달로 134-1',
    contact: '02-822-2941',
    category: 'korean',
    foodCategory: '한정식 / 백반 / 정통 한식',
    closed: '',
    open: '10:00 - 22:00',
    location: 'hs_station',
  },
  {
    name: '채홍',
    address: '서울특별시 동작구 강남초등길 24',
    contact: '02-826-8885',
    category: 'chinese',
    foodCategory: '정통 중식 / 일반 중식',
    closed: '',
    open: '',
    location: 'back',
  },
  {
    name: '미묘라멘',
    address: '서울특별시 동작구 서달로13길 4',
    contact: '02-822-8998',
    category: 'japanese',
    foodCategory: '라멘 / 소바 / 우동',
    closed: '일',
    open: '월-금: 11:30 - 20:00 토: 12:00 - 14:30',
    location: 'hs_station',
  },
  {
    name: '자담상',
    address: '서울특별시 동작구 서달로 158 2F',
    contact: '02-812-0812',
    category: 'korean',
    foodCategory: '한정식 / 백반 / 정통 한식',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '화르르',
    address: '서울특별시 동작구 흑석로 111',
    contact: '02-813-3460',
    category: 'korean',
    foodCategory: '닭 / 오리 요리',
    closed: '',
    open: '',
    location: 'front',
  },
  {
    name: '박군하누',
    address: '서울특별시 동작구 서달로15길 23 1F',
    contact: '02-821-1800',
    category: 'korean',
    foodCategory: '고기 요리',
    closed: '',
    open: '',
    location: 'hs_station',
  },
  {
    name: '호치킨',
    address: '서울특별시 동작구 서달로 165-1',
    contact: '02-3280-1550',
    category: 'western',
    foodCategory: '닭 / 오리 요리',
    closed: '일',
    open: '13:00 - 01:00',
    location: 'hs_station',
  },
];

(async () => {
  await DB.connect();
  let shopController = new ShopController();

  for (let shop of data) {
    await shopController.createShop(
      shop.name,
      shop.contact,
      shop.address,
      shop.open,
      shop.closed,
      shop.price || 0,
      shop.latitude || 0,
      shop.longitude || 0,
      shop.location as any,
      shop.category as any,
    );
  }
  console.log('Shop Insert 완료');
})();
