/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-07-29 13:33:46
 */
import Shop, { ShopInterface, ShopSchemaInterface, ShopCategory } from '../../models/Shop';
import { KeywordSchemaInterface } from '../../models/Keyword';
import { ShopOrder } from '../../../service/ShopService';

export interface IShopController {
  findById(id: string): Promise<ShopSchemaInterface | null>;

  getAllShops(): Promise<ShopInterface[] | null>;
  getShops(filter: any, order: ShopOrder): Promise<ShopInterface[] | null>;
  createShop(
    name: string,
    contact: string,
    address: string,
    image: string[],
    open: string,
    closed: string,
    location: Location,
    category: ShopCategory,
  ): Promise<ShopInterface | null>;
}
